// generated by stringer -type=Comparison; DO NOT EDIT

package cas

import "fmt"

const _Comparison_name = "LessThanEqualToGreaterThan"

var _Comparison_index = [...]uint8{0, 8, 15, 26}

func (i Comparison) String() string {
	i -= -1
	if i < 0 || i+1 >= Comparison(len(_Comparison_index)) {
		return fmt.Sprintf("Comparison(%d)", i+-1)
	}
	return _Comparison_name[_Comparison_index[i]:_Comparison_index[i+1]]
}
