// generated by stringer -type=LexError; DO NOT EDIT

package script

import "fmt"

const _LexError_name = "ErrUnterminatedSQSErrUnterminatedDQSErrUnterminatedBS"

var _LexError_index = [...]uint8{0, 18, 36, 53}

func (i LexError) String() string {
	if i+1 >= LexError(len(_LexError_index)) {
		return fmt.Sprintf("LexError(%d)", i)
	}
	return _LexError_name[_LexError_index[i]:_LexError_index[i+1]]
}
