// generated by stringer -type=TokenType; DO NOT EDIT

package script

import "fmt"

const _TokenType_name = "ErrorTokenWordTokenCommentTokenNewlineToken"

var _TokenType_index = [...]uint8{0, 10, 19, 31, 43}

func (i TokenType) String() string {
	if i+1 >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
