// Automatically generated by MockGen. DO NOT EDIT!
// Source: fs.go

package fs

import (
	gomock "github.com/golang/mock/gomock"
	os "os"
)

// Mock of FileSystem interface
type MockFileSystem struct {
	ctrl     *gomock.Controller
	recorder *_MockFileSystemRecorder
}

// Recorder for MockFileSystem (not exported)
type _MockFileSystemRecorder struct {
	mock *MockFileSystem
}

func NewMockFileSystem(ctrl *gomock.Controller) *MockFileSystem {
	mock := &MockFileSystem{ctrl: ctrl}
	mock.recorder = &_MockFileSystemRecorder{mock}
	return mock
}

func (_m *MockFileSystem) EXPECT() *_MockFileSystemRecorder {
	return _m.recorder
}

func (_m *MockFileSystem) Open(_param0 string, _param1 WriteType, _param2 IOType) (File, error) {
	ret := _m.ctrl.Call(_m, "Open", _param0, _param1, _param2)
	ret0, _ := ret[0].(File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileSystemRecorder) Open(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Open", arg0, arg1, arg2)
}

func (_m *MockFileSystem) Walk(_param0 WalkFunc) error {
	ret := _m.ctrl.Call(_m, "Walk", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileSystemRecorder) Walk(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Walk", arg0)
}

// Mock of File interface
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *_MockFileRecorder
}

// Recorder for MockFile (not exported)
type _MockFileRecorder struct {
	mock *MockFile
}

func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &_MockFileRecorder{mock}
	return mock
}

func (_m *MockFile) EXPECT() *_MockFileRecorder {
	return _m.recorder
}

func (_m *MockFile) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *MockFile) Stat() (os.FileInfo, error) {
	ret := _m.ctrl.Call(_m, "Stat")
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) Stat() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Stat")
}

func (_m *MockFile) ReadAt(_param0 []byte, _param1 int64) (int, error) {
	ret := _m.ctrl.Call(_m, "ReadAt", _param0, _param1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) ReadAt(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadAt", arg0, arg1)
}

func (_m *MockFile) WriteAt(_param0 []byte, _param1 int64) (int, error) {
	ret := _m.ctrl.Call(_m, "WriteAt", _param0, _param1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFileRecorder) WriteAt(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WriteAt", arg0, arg1)
}

func (_m *MockFile) Sync() error {
	ret := _m.ctrl.Call(_m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileRecorder) Sync() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Sync")
}

func (_m *MockFile) Truncate(_param0 int64) error {
	ret := _m.ctrl.Call(_m, "Truncate", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileRecorder) Truncate(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Truncate", arg0)
}

func (_m *MockFile) PunchHole(off int64, n int64) error {
	ret := _m.ctrl.Call(_m, "PunchHole", off, n)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFileRecorder) PunchHole(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PunchHole", arg0, arg1)
}
