// generated by stringer -type=Action; DO NOT EDIT

package auth

import "fmt"

const _Action_name = "DenyAllow"

var _Action_index = [...]uint8{0, 4, 9}

func (i Action) String() string {
	if i+1 >= Action(len(_Action_index)) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
