// generated by stringer -type=Operation; DO NOT EDIT

package auth

import "fmt"

const _Operation_name = "AnyStatFSWalkGetPutRemove"

var _Operation_index = [...]uint8{0, 3, 9, 13, 16, 19, 25}

func (i Operation) String() string {
	if i+1 >= Operation(len(_Operation_index)) {
		return fmt.Sprintf("Operation(%d)", i)
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
