// generated by stringer -type=IOType; DO NOT EDIT

package fs

import "fmt"

const _IOType_name = "NormalIODirectIO"

var _IOType_index = [...]uint8{0, 8, 16}

func (i IOType) String() string {
	i -= 1
	if i+1 >= IOType(len(_IOType_index)) {
		return fmt.Sprintf("IOType(%d)", i+1)
	}
	return _IOType_name[_IOType_index[i]:_IOType_index[i+1]]
}
