// generated by stringer -type=WriteType; DO NOT EDIT

package fs

import "fmt"

const _WriteType_name = "ReadOnlyReadWrite"

var _WriteType_index = [...]uint8{0, 8, 17}

func (i WriteType) String() string {
	i -= 1
	if i+1 >= WriteType(len(_WriteType_index)) {
		return fmt.Sprintf("WriteType(%d)", i+1)
	}
	return _WriteType_name[_WriteType_index[i]:_WriteType_index[i+1]]
}
